-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "fileName" TEXT;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "fileMime" TEXT;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "fileData" BYTEA;
